source 'https://rubygems.org'

gem "cucumber", "= 1.3.10"
gem 'gherkin', '= 2.12.2'
gem "headless", "= 0.3.1"
gem "json_spec", "= 1.1.1"
gem "mail", "= 2.5.4"
gem "rspec-expectations", "= 2.14.4"
gem "selenium-webdriver", "= 2.37.0"
gem "rubyzip", "~> 1.0.0"
